export const datos_tecnicos = [
  {
    id: 1,
    imagen: "/imagen/anillo-plano-de-hidrocoloide.jpg",
    producto: "anillo-plano-de-hidrocoloide",
    descripcion: "descripcion",
    precio: 155,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 2,
    imagen: "/imagen/aspirador.jpg",
    producto: "aspirador",
    descripcion: "descripcion",
    precio: 160,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 3,
    imagen: "/imagen/baston-con-mango-en-t-regulable.jpg",
    producto: "baston-con-mango-en-t-regulable",
    descripcion: "descripcion",
    precio: 200,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 4,
    imagen: "/imagen/cojin-de-gel-encapsulado-antiescara-airgel.jpg",
    producto: "cojin-de-gel-encapsulado-antiescara-airgel",
    descripcion: "descripcion",
    precio: 60,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 5,
    imagen: "/imagen/concentrador-de-oxigeno-chart.jpg",
    producto: "concentrador-de-oxigeno-chart",
    descripcion: "descripcion",
    precio: 100,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 6,
    imagen: "/imagen/estuche.jpg",
    producto: "estuche",
    descripcion: "descripcion",
    precio: 110,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 7,
    imagen: "/imagen/humidificador.jpg",
    producto: "humidificador",
    descripcion: "descripcion",
    precio: 40,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 8,
    imagen: "/imagen/jeringa-descartable.jpg",
    producto: "jeringa-descartable",
    descripcion: "descripcion",
    precio: 608,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 9,
    imagen: "/imagen/nebulizador.jpg",
    producto: "nebulizador",
    descripcion: "descripcion",
    precio: 67,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 10,
    imagen: "/imagen/protector-impermeable-de-superficies-theraproff.jpg",
    producto: "protector-impermeable-de-superficies-theraproff",
    descripcion: "descripcion",
    precio: 960,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 11,
    imagen: "/imagen/tensiometro (1).jpg",
    producto: "tensiometro (1)",
    descripcion: "descripcion",
    precio: 350,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 12,
    imagen: "/imagen/tensiometro.jpg",
    producto: "tensiometro",
    descripcion: "descripcion",
    precio: 120,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 13,
    imagen: "/imagen/tiras.jpg",
    producto: "tiras",
    descripcion: "descripcion",
    precio: 220,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 14,
    imagen: "/imagen/termometro-infrarrojo-de-frente-y-oido.jpg",
    producto: "termometro-infrarrojo-de-frente-y-oido",
    descripcion: "descripcion",
    precio: 160,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
  {
    id: 15,
    imagen: "/imagen/termometro.jpg",
    producto: "termometro",
    descripcion: "descripcion",
    precio: 90,
    caracteristica_uno: "caracteristica_uno",
    caracteristica_uno2: "caracteristica_uno2",
    caracteristica_uno3: "caracteristica_uno3",
    caracteristica_uno4: "caracteristica_uno4",
  },
];
